# Generated by Django 4.0.6 on 2022-08-24 21:45

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Engineer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('job', models.CharField(max_length=5)),
                ('age', models.CharField(max_length=2)),
                ('email', models.EmailField(max_length=200)),
                ('message', models.TextField()),
                ('phone', models.CharField(max_length=10)),
                ('birthday', models.DateField()),
                ('personality', models.CharField(choices=[('', 'Select a personality'), ('I am introvert ', 'I am introvert '), ('I am extrovert ', 'I am extrovert '), ('I am sociable ', 'I am sociable '), ('I am antisociable ', 'I am antisociable '), ('I am serious', 'I am serious')], max_length=50, null=True)),
                ('salary', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=7)),
                ('experience', models.BooleanField(null=True)),
                ('file', models.FileField(blank=True, upload_to='documents/', verbose_name='CV')),
                ('image', models.ImageField(null=True, upload_to='images/', verbose_name='Image')),
                ('smoker', models.CharField(choices=[('1', 'Yes'), ('2', 'No')], default='', max_length=3, null=True)),
                ('situation', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Dissaproved', 'Dissaproved')], default='Pending', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('frameworks', multiselectfield.db.fields.MultiSelectField(choices=[('Laravel', 'Laravel'), ('Angular', 'Angular'), ('Django', 'Django'), ('Flask', 'Flask'), ('Vue', 'Vue'), ('Other', 'Other')], default='', max_length=38)),
                ('languages', multiselectfield.db.fields.MultiSelectField(choices=[('Python', 'Python'), ('Php', 'Php'), ('Javascript', 'Javascript'), ('C++', 'C++'), ('Java', 'Java'), ('Other', 'Other')], default='', max_length=36)),
                ('databases', multiselectfield.db.fields.MultiSelectField(choices=[('MySql', 'MySql'), ('Postgree', 'Postgree'), ('MongoDB', 'MongoDB'), ('SqLite3', 'SqLite3'), ('Oracle', 'Oracle'), ('Other', 'Other')], default='', max_length=43)),
                ('libraries', multiselectfield.db.fields.MultiSelectField(choices=[('Ajax', 'Ajax'), ('Jquery', 'Jquery'), ('React', 'React'), ('Char.js', 'Char.js'), ('BootsTrap', 'BootsTrap'), ('Other', 'Other')], default='', max_length=41)),
                ('mobile', multiselectfield.db.fields.MultiSelectField(choices=[('React Native', 'React Native'), ('Kivy', 'Kivy'), ('Flutter', 'Flutter'), ('Ionic', 'Ionic'), ('Xamarim', 'Xamarim'), ('Other', 'Other')], default='', max_length=45)),
                ('other', multiselectfield.db.fields.MultiSelectField(choices=[('UML', 'UML'), ('SQL', 'SQL'), ('Docker', 'Docker'), ('GIT', 'GIT'), ('GraphQL', 'GraphQL'), ('Others', 'Others')], default='', max_length=33)),
                ('university', models.CharField(max_length=50)),
                ('faculty', models.CharField(max_length=50)),
                ('institution', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=50)),
                ('start_course', models.DateField()),
                ('end_course', models.DateField()),
                ('about_course', models.TextField()),
                ('status_course', models.CharField(choices=[('', 'Select a status'), ("I'm studying ", "I'm studying"), ("I'm took a break ", "I'm took a break "), ('Completed ', 'Completed')], max_length=50, null=True)),
                ('company', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
                ('start_work', models.DateField()),
                ('end_work', models.DateField()),
                ('about_work', models.TextField()),
                ('employed', models.BooleanField(null=True, verbose_name="I'm employe")),
                ('travel', models.BooleanField(null=True, verbose_name="I'm available for travel")),
                ('remote', models.BooleanField(null=True, verbose_name="I'm to remote work")),
            ],
        ),
    ]
